# Generated by Django 3.0.6 on 2020-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('problem', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('creat_time', models.DateField()),
            ],
            options={
                'db_table': 'emp_login',
            },
        ),
    ]
